<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGI9glz2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGI9glz2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGI9glz2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGI9glz2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGI9glz2\App_KernelDevDebugContainer([
    'container.build_hash' => 'GI9glz2',
    'container.build_id' => 'c34f32d2',
    'container.build_time' => 1624903593,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGI9glz2');
